/* pilrc generated file.  Do not edit!*/
#define InsufficientPlayersAlert 9954
#define PlayerNamesAlert 9955
#define MoveButton 9956

#define Armies0 9957
#define Armies1 9958
#define Armies2 9959
#define Armies3 9960
#define Armies4 9961
#define Armies5 9962
#define Armies6 9963
#define Armies7 9964
#define Armies8 9965
#define Armies9 9966

#define PalmwarsNumArmiesForm 9967
#define PalmwarsGameForm 9968
#define PalmwarsAboutForm 9969

#define BeginButton 9970
#define Player1Name 9971
#define Player2Name 9972
#define Player3Name 9973
#define Player4Name 9974

#define Player1Label 9975
#define Player2Label 9976
#define	Player3Label 9977
#define	Player4Label 9978
#define MabsCheckbox 9979

#define NumPlayers1 9980
#define NumPlayers2 9981
#define NumPlayers3 9982
#define NumPlayers4 9983

#define PlayersLabel 9984
#define SectorList 9985
#define SectorTrigger 9986
#define SectorLabel 9987
#define PalmwarsLabel 9988
#define PalmwarsStartForm 9989
#define About 9990
#define NewGame 9991
#define PalmwarsMenuBar 9992

#define Label 9993
#define OkButton 9994
#define CancelButton 9995

//
// Autogenerated symbols - 17/05/2003 13:09:25
// Falch.net PilRC Designer
//
#define MapData 8000
#define PalmwarsBitmap 8001
//
// Autogenerated symbols - 17/05/2003 15:35:05
// Falch.net PilRC Designer
//
#define	AT	1005
//
// Autogenerated symbols - 20/05/2003 23:44:12
// Falch.net PilRC Designer
//
#define	PalmwarsSectorForm	1004
#define	Version	1009
//
// Autogenerated symbols - 02/06/2003 20:17:15
// Falch.net PilRC Designer
//
#define	LauncherCategory	1000
//
// Autogenerated symbols - 02/06/2003 20:41:21
// Falch.net PilRC Designer
//
#define	PassButton	1003
//
// Autogenerated symbols - 09/06/2003 23:05:44
// Falch.net PilRC Designer
//
#define	PalmwarsSmallMenu	1008
//
// Autogenerated symbols - 09/06/2003 23:08:59
// Falch.net PilRC Designer
//
#define	SectorScrollbar	1005
//
// Autogenerated symbols - 11/06/2003 16:25:19
// Falch.net PilRC Designer
//
#define	SectorName	1006
#define	LeftArrowBitmap	1016
//
// Autogenerated symbols - 11/06/2003 16:27:19
// Falch.net PilRC Designer
//
#define	RightArrowBitmap	1017
#define	RightArrowButton	1005
//
// Autogenerated symbols - 11/06/2003 16:35:09
// Falch.net PilRC Designer
//
#define	LeftArrowButton	1007
#define	LeftArrowSelBitmap	1018
#define	RightArrowSelBitmap	1019
