//	Header generated by Constructor for Palm OS (R) 1.8
//
//	Generated at 00:12:35  on 18 March 2003
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE
//	DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"Untitled"
//
//	Palm App Version:		"1.0"


//	Resource: tFRM 1000
#define PalmwarsStartFormForm                     1000
#define PalmwarsStartFormBeginButtonButton        1010
#define PalmwarsStartFormMabsCheckboxCheckbox     1005
#define PalmwarsStartFormPlayer1NameField         1006
#define PalmwarsStartFormPlayer2NameField         1007
#define PalmwarsStartFormPlayer3NameField         1008
#define PalmwarsStartFormPlayer4NameField         1009
#define PalmwarsStartFormSectorListList           1011
#define PalmwarsStartFormNumPlayers1PushButton    1001
#define PalmwarsStartFormNumPlayers2PushButton    1002
#define PalmwarsStartFormNumPlayers3PushButton    1003
#define PalmwarsStartFormNumPlayers4PushButton    1004
#define PalmwarsStartFormUnnamed1012PopTrigger    1012

